### ISSUE TITLE
DVCC - Limit DCL/ / CCL

### ISSUE THREAD

**Issue by fadnincx** [123electric/smartbms-venus#24]
Having "Dual range 125A -5A" as current sensor configured should at least give me the opportunity to limit the DCL/CCL to 125A, because the cable and fuse are dimensioned for this maximum configuration. Generally having the option in Venus to set these limits to an arbitrary maximum would be extremely nice.

Currently DCL and CCL are set to 265A (1C) if not limited by some other factor.

Or is this already possible and I missed a setting?

---
Used versions (all latest afaik):
BMS firmware v3.2.13
Venus firmware v3.0.0
123Smartbms-Venus v1.10

**Comment by AlexW85** [comment]
I have the same question. I have 64x LiFePO4 Cells in 4 Banks with 280ah each. 🤭 My CCL is 1092A from the 123SmartBMS Manager. I won't charge with so high Power! Theoretical the MPPTs in sum can "only" 600A, DVCC in Victron is ignored, because 123BMS is the master and should it be. It would be nice if we can set a max CCL. My preference will be 250A to the batterie, and the other theoretical 350A directly into the Grid. More is not needed and will improve Lifetime.

1092A is by the way not possible too, cables and connectors are thick enough (95mm²), but i only have 160A NH Fuses in each bank.

**Comment by AlbertronicDev** [comment]
Hi,
The 123\SmartBMS Venus software cannot easily add configurable settings: we have to adapt to the Victron battery interface. Thus, we choose to set the value to 1C.
However, there are Victron settings which you can use to limit the charge/discharge current.
You can also fork this repository and change the CCL and DCL value rate of 1C in the smartbms_manager.py code to what you want. Then in the GX, go to Settings->Package Manager->Active packages->123SmartBMS Venus and change the user and branch to your own to use your forked version with your own values.
