### ISSUE TITLE
Feature Request to ignore the temperature low setting for the load allowed relay

### ISSUE THREAD

**Issue by JTG-IX** [123electric/smartbms-venus#4]
I believe the newer generation has this option to keep allowing loads when the temperature drops below a set value. For me, having the 2nd generation BMS, it always requires me to set the temperature value to the lowest possible rendering it useless and unplug all charge controllers from the 'allow to charge' relay manually. Otherwise both charging as well as loads are allowed which is not good for the battery obviously.

Better would be to be able to set the temperature value to realistic one; controlling the chargers to stop charging below the set temperature value whilst keeping the loads allowed.

Would it be possible to make such a control through the venus menu options?

The current behaviour when the temperature gets above the set values is ok.

**Comment by CodeChief** [comment]
I think the DBUS of Victron/VenusOS should be controlling the "allow to charge" and "allow to discharge" of any Victron Solar or Multi/Pheonix-Smart (VE Bus/Direct enabled) chargers. Otherwise, we would have to physically connect the relay signal lines of the BMS to each charger to achieve the "2 wire BMS control" option as supported in the Victron "Assistant" concept.

What I am looking for, is evidence/documentation that this current implementation supports passing on the state of the "allow to charge" and "allow to discharge" to the VE.Bus or VE.Direct devices. Recently I had an overvolt situation during charging on a Multiplus connected via VE.Bus to the RasPi VenusOS image with the latest version of 123BMS integration. I had to manually intervene as I was worried but am not sure if it would have disabled it anyway. Also, I'm worried that somehow the integration is preventing the normal operation of the 123BMS relay (it did not physically switch off in my case but did before in my tests directly with just the 123BMS App).

Currently I only have one physical relay for the same reason (I understand) as you, as Victron devices commonly support both charging and discharging it's not always possible to wire-up separately/simply with 2 relays fully controlled by 123BMS. So I set the 123BMS correctly to "critical mode". However, when looking at the Victron "view" of the system, it says under the Victron Settings -> System setup -> System status (note menu item System status is in orange/warning state) that "Solar charger current control" and "BMS control" are off:

![image](https://user-images.githubusercontent.com/1496225/142267568-53eb5d3b-0e45-462d-ac34-06eff17720dc.png)

Either I did not configure it correctly due to missing documentation, or the current 123BMS integration needs to be updated to appear fully integrated.

I think we need to cross-check the source against the https://github.com/Louisvdw/dbus-serialbattery GitHub project as they appear to have some advanced implementations for other BMS systems and I presume they support all possible features as a relatively mature open source project.

**Comment by JTG-IX** [comment]
That would be ideal setup IF you can have the 2 wire assistant. I am using a multiplus compact 12/1600-70 so I can only use the temp ‘input’ to signal stop charging. To still accomplish a full setup I use signal relays to control the Orion and MPPT via remote control wires.

**Comment by CodeChief** [comment]
We have almost the same setup except the Orion. As I understand it, the whole point of the GX devices (Venus OS) is to bridge the multiple "smart" bus systems and share voltage, temperature, current, alarm/signal status and control logic.

I assumed there should be no need to physically connect anything except the VE.Direct, VE.Bus and 123BMS communication cables. That makes sense why bother even integrating the BMS if all it does is provide voltage and current (I already have a Victron SmartShunt for that).

The Victron BMS settings sadly only work with Victron batteries/BMS. The documentation states external BMS should be selected. I think we are missing a virtual switch assistant configuration, if the DBUS drivers of VenusOS have no direct ability to influence the charge/discharge disabled and there is no workaround by triggering alarms/other logic.

It's visible (see screenshot of last post) that BMS control and solar charger control are possible in the system setup status. The question is, best asked on the other repository, is how does it look with other BMS integrations? Is this at all possible without a Victron battery or some other custom switch or assistant development.

**Comment by JTG-IX** [comment]
Well, like I mentioned I use a set of relays for the control. What I am missing is the possibility to have the ‘load allow’ relay ignore the low temp value. For instance to start the fan on the diesel heater to increase the overall temperature. That is why I made this feature request ;-)

I also have the Smartshunt, it does not agree with the SOC of the smart123 BMS all of the time. (Usually only after full charge)

**Comment by AlbertronicDev** [comment]
The 123\SmartBMS Venus code + cable was developed for customers to see the BMS data on the CCGX and/or remote monitor it via VRM, which works now. You can even work without BMV and select the 123\SmartBMS as battery monitor if you have a gen3 set. For gen2 this is not recommended as those current sensors were not sensitive enough.

It would be nice if the Victron would listen to the SmartBMS to stop charging and/or discharging. Even though we pass some paths including "allowed to charge" and "allow to discharge" via the dbus, it does not seem like the Victron does anything with it, besides displaying. We have not found any documentation how to make a fully BMS control version. We know this is possible via CAN bus (physical), not sure via dbus. I expect it would be possible.

In Louisvdw's code, I also see some paths which we currently not use:
/Info/MaxChargeVoltage etc. I will add these next week and try out if this gives a "yes" on the BMS control.

About the feature request: the BMS only transmits data to the Venus so we won't be able to modify anything on the BMS like settings. Because the code currently only works as battery monitor, it does not make sense to add anything customizing the thresholds. If we get the full BMS support working, it can help for gen2 systems.

For now, you still need to connect an energy efficient power relay to the 123\SmartBMS signal relays or the remote wire from the Victron to the 123\SmartBMS signal relays. The benefit of a power relay is that if a Victron would ever fail and keep discharging/charging, or just if a device has some leakage current, the BMS can fully disconnect that device to protect the battery."

Let's keep this topic purely for this feature request. I have created a separate feature request for DVCC/BMS support: [https://github.com/123electric/smartbms-venus/issues/5](https://github.com/123electric/smartbms-venus/issues/5)

**Comment by AlbertronicDev** [comment]
It's been some time since this request. The 123\SmartBMS Venus software supports active control now.

Adding new features to 123\SmartBMS gen1/gen2, like the separate Tmin charge, is not possible as gen1/gen2 does not support firmware updates.

People with 123\SmartBMS gen3 do already have this separate Tmin charge and Tmin discharge.

Adding this as a setting in the Victron GUI involves some development but especially extra long term maintenance as we then need to keep up-to-date with the Victron GUI. So we decided to not add anything graphical/not modify the Victron GUI, but purely make the software compatible with the standard Victron BMS GUI page (as you see).

For now, this ticket can be closed as it is unlikely that we can/will add this feature.
