### ISSUE TITLE
use timeout on cell disconnect

### ISSUE THREAD

**Issue by Korenchkin** [123electric/smartbms-venus#8]
hello,
i've discovered on latest code that if i pull some cell cable(simulate something broken/failed module/etc.) that end module disable relays,but victron keeps going on latest values delivered(since last cell module just stops transmitting),is it possible to add some timeout check and kill load/charging? killing load/charging works after reconnect,when fail is delivered on first message after interrupt
thanks,
pb

**Comment by AlbertronicDev** [comment]
Hi,

Which version are you using, v0.9 from the website or the beta (v1.2) via kwindem's, PackageManager? V0.9 does not support any active Victron control, v1.2 does but is in beta.

**Comment by Korenchkin** [comment]
Hello,latest beta...i'm not a programmer myself,but i can understand what it does,so when the communication stops,the latest module stops,so this needs to be in code,as the last module won't send the problem,so this will need bigger code change probably?
Edit:i did not test latest 6 days old beta yet as of now...

**Comment by AlbertronicDev** [comment]
Hi,
Thanks for letting me know. I will do some tests and fix it (if not already done) in the new coming beta.

**Comment by AlbertronicDev** [comment]
Hi Korenchkin,

We fixed this in the last update. Please let me know if it fixed your issue.

**Comment by Korenchkin** [comment]
hello,
so,i tested it thoroughly,here is what happens after breaking cell communication:
stopping charging works,after several 10's of seconds mppt goes from bms managed to something like 'keep' (sorry,translating from czech),which stops charge,but i think this is possibly only side-effect,there is really no other option to use in bms software than timeout(for example 10s after last message?to be on a safe side?) to set max charge current and max discharge current to 0(or allow to charge and allow to discharge =no,which presumably sets currents to 0)

after reconnecting the cell back first message gets to ccgx and multiplus goes down(because during this time allow discharge=no message gets there)...then mppt starts to charge slowly and multiplus starts again

(semi-island,i have line,but i chose to keep it off to really stay away from even very small feed-in,crappy laws here)
tested latest 1.3~8, DVCC ON, 24V 8cell LFP 3.4V (dvcc works well,charging to something ~27.4V to balance for a minute,then backing to ~26.88V)
thanks

**Comment by AlbertronicDev** [comment]
Hi,
Thanks for testing.
The 30 second timeout is correct. This is done on purpose: we discovered that a USB instance can disconnect from time to time, maybe because of EMF pulse. It takes about 15 seconds to restart the USB code, so we want to be sure the Manager does not stop the Victron meanwhile. That is why the timeout is 30 seconds. Don't worry, in 30 seconds the battery will not be over or undercharged.

We found a small bug which can make the Manager crash (and restart), will fix it directly.
Thanks for testing!

**Comment by Korenchkin** [comment]
hello,thanks for the fix,maybe i wasn't waiting long enough for shutdown to trigger,i had time today to test different conditions and after disconnecting cell it took around 2 minutes before multiplus went offline,cerbo already in alarm conditions and multipluses were still online,it took some time...
after reconnecting alarm cleared itself and multipluses started,so this works beautifull


//* another possible issue starts here *//
now i have to test bulk/float charging,in some not too past version i had to restart cerbo for charging to start,because bms was holding batteries hostage(another day it would not charge to full,also this might be connected to soc calculation only,voltage was holding to 26.88 if i remember correctly on 24v system,but soc was dropping each day to around 50%,after 7 days it shifted max voltage to something 27.4,not sure exactly,and this led firmware on bms to set soc to 100%,but charge didn't look like 50% of a battery capacity,i believe part of the problem is too low current,below 4amps on 2 turns of wire through dual current sensor)
i'm putting it here in case somebody has some idea,when/if i can precisely replicate what's wrong,i will make new issue to keep this clean

thanks,
k.

**Comment by AlbertronicDev** [comment]
Hi,

When the battery cells are full and balanced, the BMS will lower the max charge voltage to 40mV below Vbalance (per cell), so the cells will not keep balancing all the time for nothing. So if your Vbalance is 3.4V, the code will keep the cells at about 3.36V per cell (max). In the early version, this is reset every 7 days or when disbalance is detected. In the new code, it is reduced to 4 days. So every 4 days, the BMS will let the cells balance again.

If you notice there is still an issue, for example that you see that balancing is needed within 4 days because you charge and discharge a lot, then please let us know.
